var annotated_dup =
[
    [ "Potentials", null, [
      [ "EnergyFactor", "structPotentials_1_1EnergyFactor.html", null ],
      [ "GradientFactor", "structPotentials_1_1GradientFactor.html", null ],
      [ "HessianFactor", "structPotentials_1_1HessianFactor.html", null ],
      [ "TricubicDerivativeFactor", "structPotentials_1_1TricubicDerivativeFactor.html", null ],
      [ "TriquinticDerivativeFactor", "structPotentials_1_1TriquinticDerivativeFactor.html", null ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< MultiSiteIsotherm >", "structstd_1_1hash_3_01MultiSiteIsotherm_01_4.html", null ]
    ] ],
    [ "Atom", "structAtom.html", "structAtom" ],
    [ "BlockErrorEstimation", "structBlockErrorEstimation.html", "structBlockErrorEstimation" ],
    [ "BondPotential", "structBondPotential.html", "structBondPotential" ],
    [ "Breakthrough", "structBreakthrough.html", null ],
    [ "BreakthroughSimulation", "structBreakthroughSimulation.html", null ],
    [ "ChainData", "structChainData.html", null ],
    [ "ChargeEquilbrationElementData", "structChargeEquilbrationElementData.html", null ],
    [ "CIFReader", "structCIFReader.html", "structCIFReader" ],
    [ "Component", "structComponent.html", "structComponent" ],
    [ "EnergyInter", "structEnergyInter.html", null ],
    [ "EnergyIntra", "structEnergyIntra.html", null ],
    [ "EnergyOpenCLSurfaceArea", "structEnergyOpenCLSurfaceArea.html", null ],
    [ "EnergyOpenCLVoidFraction", "structEnergyOpenCLVoidFraction.html", null ],
    [ "EnergyStatus", "structEnergyStatus.html", null ],
    [ "EnergySurfaceArea", "structEnergySurfaceArea.html", null ],
    [ "EnergyVoidFraction", "structEnergyVoidFraction.html", null ],
    [ "EnthalpyOfAdsorption", "structEnthalpyOfAdsorption.html", null ],
    [ "EnthalpyOfAdsorptionTerms", "structEnthalpyOfAdsorptionTerms.html", null ],
    [ "EquationOfState", "structEquationOfState.html", "structEquationOfState" ],
    [ "FirstBeadData", "structFirstBeadData.html", null ],
    [ "ForceField", "structForceField.html", "structForceField" ],
    [ "Framework", "structFramework.html", "structFramework" ],
    [ "GrowingStatus", "structGrowingStatus.html", null ],
    [ "InputDataSystem", "structInputDataSystem.html", "structInputDataSystem" ],
    [ "InputReader", "structInputReader.html", "structInputReader" ],
    [ "IntegratorsCPUTime", "structIntegratorsCPUTime.html", null ],
    [ "InterpolationEnergyGrid", "structInterpolationEnergyGrid.html", null ],
    [ "Isotherm", "structIsotherm.html", null ],
    [ "IsothermFitting", "structIsothermFitting.html", "structIsothermFitting" ],
    [ "IsothermFittingSimulation", "structIsothermFittingSimulation.html", null ],
    [ "Loadings", "structLoadings.html", null ],
    [ "MC_OpenCL_PoreSizeDistribution", "structMC__OpenCL__PoreSizeDistribution.html", null ],
    [ "MC_OpenCL_SurfaceArea", "structMC__OpenCL__SurfaceArea.html", null ],
    [ "MC_OpenCL_VoidFraction", "structMC__OpenCL__VoidFraction.html", null ],
    [ "MC_PoreSizeDistribution", "structMC__PoreSizeDistribution.html", null ],
    [ "MC_SurfaceArea", "structMC__SurfaceArea.html", null ],
    [ "MC_VoidFraction", "structMC__VoidFraction.html", null ],
    [ "MCMoveCpuTime", "structMCMoveCpuTime.html", "structMCMoveCpuTime" ],
    [ "MCMoveProbabilities", "structMCMoveProbabilities.html", null ],
    [ "MCMoveStatistics", "structMCMoveStatistics.html", null ],
    [ "MixturePrediction", "classMixturePrediction.html", null ],
    [ "MixturePredictionSimulation", "structMixturePredictionSimulation.html", null ],
    [ "MolecularDynamics", "structMolecularDynamics.html", "structMolecularDynamics" ],
    [ "Molecule", "structMolecule.html", "structMolecule" ],
    [ "MonteCarlo", "structMonteCarlo.html", "structMonteCarlo" ],
    [ "MonteCarloTransitionMatrix", "structMonteCarloTransitionMatrix.html", "structMonteCarloTransitionMatrix" ],
    [ "MoveStatistics", "structMoveStatistics.html", "structMoveStatistics" ],
    [ "MultiSiteIsotherm", "structMultiSiteIsotherm.html", null ],
    [ "PressureRange", "structPressureRange.html", null ],
    [ "PropertyConventionalRadialDistributionFunction", "structPropertyConventionalRadialDistributionFunction.html", null ],
    [ "PropertyDensityGrid", "structPropertyDensityGrid.html", null ],
    [ "PropertyEnergy", "structPropertyEnergy.html", null ],
    [ "PropertyEnergyHistogram", "structPropertyEnergyHistogram.html", null ],
    [ "PropertyEnthalpy", "structPropertyEnthalpy.html", null ],
    [ "PropertyLambdaProbabilityHistogram", "structPropertyLambdaProbabilityHistogram.html", null ],
    [ "PropertyLoading", "structPropertyLoading.html", "structPropertyLoading" ],
    [ "PropertyMeanSquaredDisplacement", "structPropertyMeanSquaredDisplacement.html", null ],
    [ "PropertyNumberOfMoleculesHistogram", "structPropertyNumberOfMoleculesHistogram.html", null ],
    [ "PropertyPressure", "structPropertyPressure.html", null ],
    [ "PropertyRadialDistributionFunction", "structPropertyRadialDistributionFunction.html", null ],
    [ "PropertySimulationBox", "structPropertySimulationBox.html", null ],
    [ "PropertyTemperature", "structPropertyTemperature.html", null ],
    [ "PropertyVelocityAutoCorrelationFunction", "structPropertyVelocityAutoCorrelationFunction.html", null ],
    [ "PropertyWidom", "structPropertyWidom.html", "structPropertyWidom" ],
    [ "PseudoAtom", "structPseudoAtom.html", "structPseudoAtom" ],
    [ "Reaction", "structReaction.html", "structReaction" ],
    [ "Reactions", "structReactions.html", "structReactions" ],
    [ "RunningEnergy", "structRunningEnergy.html", "structRunningEnergy" ],
    [ "SampleMovie", "structSampleMovie.html", null ],
    [ "SimulationBox", "structSimulationBox.html", "structSimulationBox" ],
    [ "System", "structSystem.html", "structSystem" ],
    [ "Thermostat", "structThermostat.html", "structThermostat" ],
    [ "TransitionMatrix", "structTransitionMatrix.html", "structTransitionMatrix" ],
    [ "VDWParameters", "structVDWParameters.html", "structVDWParameters" ]
];