module;

#ifdef USE_LEGACY_HEADERS
#include <cstddef>
#include <cstdlib>
#include <map>
#include <set>
#include <string>
#include <type_traits>
#include <vector>
#endif

module skelement;

#ifndef USE_LEGACY_HEADERS
import std;
#endif

SKElement::SKElement() {}

SKElement::SKElement(std::string string, std::size_t atomicNumber, std::make_signed_t<std::size_t> group,
                     std::size_t period, std::string name, double mass, double atomRadius, double covalentRadius,
                     double singleBondCovalentRadius, double doubleBondCovalentRadius, double tripleBondCovalentRadius,
                     double vDWRadius, std::vector<int> possibleOxidationStates)
    : _chemicalSymbol(string),
      _atomicNumber(atomicNumber),
      _group(group),
      _period(period),
      _name(name),
      _mass(mass),
      _atomRadius(atomRadius),
      _covalentRadius(covalentRadius),
      _singleBondCovalentRadius(singleBondCovalentRadius),
      _doubleBondCovalentRadius(doubleBondCovalentRadius),
      _tripleBondCovalentRadius(tripleBondCovalentRadius),
      _VDWRadius(vDWRadius),
      _possibleOxidationStates(possibleOxidationStates)
{
}

// van der Waals: https://periodic.lanl.gov/1.shtml
// Van der Waals Radii of Elements, S. S. Batsanov
// https://physlab.lums.edu.pk/images/f/f6/Franck_ref2.pdf
std::vector<SKElement> PredefinedElements::predefinedElements = {
    //                                                                                    mass         r      cov   1 2
    //                                                                                    3     vdw
    SKElement(std::string(""), 0, 0, 0, std::string(""), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, std::vector<int>{{}}),
    SKElement(std::string("H"), 1, 1, 1, "Hydrogen", 1.00794, 0.53, 0.31, 0.32, 0.0, 0.0, 1.20,
              std::vector<int>{-1, 1}),
    SKElement(std::string("He"), 2, 18, 1, "Helium", 4.002602, 0.31, 0.28, 0.46, 0.0, 0.0, 1.40, std::vector<int>{0}),
    SKElement(std::string("Li"), 3, 1, 2, "Lithium", 6.9421, 1.67, 1.28, 1.33, 1.24, 0.0, 1.82, std::vector<int>{1}),
    SKElement(std::string("Be"), 4, 2, 3, "Beryllium", 9.012182, 1.12, 0.96, 1.02, 0.90, 0.85, 1.53,
              std::vector<int>{1, 2}),
    SKElement(std::string("B"), 5, 13, 2, "Boron", 10.881, 0.87, 0.84, 0.85, 0.78, 0.73, 1.92,
              std::vector<int>{-5, -1, 1, 2, 3}),
    SKElement(std::string("C"), 6, 14, 2, "Carbon", 12.0107, 0.67, 0.76, 0.75, 0.67, 0.60, 1.70,
              std::vector<int>{-4, -3, -2, -1, 0, 1, 2, 3, 4}),
    SKElement(std::string("N"), 7, 15, 2, "Nitrogen", 14.0067, 0.56, 0.71, 0.71, 0.60, 0.54, 1.55,
              std::vector<int>{-3, -2, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("O"), 8, 16, 2, "Oxygen", 15.9994, 0.48, 0.66, 0.63, 0.57, 0.53, 1.52,
              std::vector<int>{-2, 1, 1, 2}),
    SKElement(std::string("F"), 9, 17, 2, "Fluorine", 18.9984032, 0.42, 0.57, 0.64, 0.59, 0.53, 1.47,
              std::vector<int>{-1}),
    SKElement(std::string("Ne"), 10, 18, 2, "Neon", 20.1797, 0.38, 0.58, 0.67, 0.96, 0.0, 1.54, std::vector<int>{0}),
    SKElement(std::string("Na"), 11, 1, 3, "Sodium", 22.98976928, 1.90, 1.66, 0.55, 1.60, 0.0, 2.27,
              std::vector<int>{-1, 1}),
    SKElement(std::string("Mg"), 12, 2, 3, "Magnesium", 24.305, 1.45, 1.41, 1.39, 1.32, 1.27, 1.73,
              std::vector<int>{1, 2}),
    SKElement(std::string("Al"), 13, 13, 3, "Aluminum", 26.9815386, 1.18, 1.21, 1.26, 1.13, 1.11, 1.84,
              std::vector<int>{-2, -1, 1, 2, 3}),
    SKElement(std::string("Si"), 14, 14, 3, "Silicon", 28.0855, 1.11, 1.11, 1.16, 1.07, 1.02, 2.10,
              std::vector<int>{-4, -3, -2, -1, 1, 2, 3, 4}),
    SKElement(std::string("P"), 15, 15, 3, "Phosphorus", 30.973762, 0.98, 1.07, 1.11, 1.02, 0.94, 1.80,
              std::vector<int>{-3, -2, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("S"), 16, 16, 3, "Sulfur", 32.065, 0.88, 1.05, 1.03, 0.94, 0.95, 1.80,
              std::vector<int>{-2, -1, 1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Cl"), 17, 17, 3, "Chlorine", 35.453, 0.79, 1.02, 0.99, 0.95, 0.93, 1.75,
              std::vector<int>{-1, 1, 2, 3, 4, 5, 6, 7}),
    SKElement(std::string("Ar"), 18, 18, 3, "Argon", 39.948, 0.71, 1.06, 0.96, 1.07, 0.96, 1.88, std::vector<int>{0}),
    SKElement(std::string("K"), 19, 1, 4, "Potassium", 39.0983, 2.43, 2.03, 1.96, 1.93, 0.0, 2.75,
              std::vector<int>{-1, 1}),
    SKElement(std::string("Ca"), 20, 2, 4, "Calcium", 40.078, 1.94, 1.76, 1.71, 1.47, 1.33, 2.31,
              std::vector<int>{1, 2}),
    SKElement(std::string("Sc"), 21, 3, 4, "Scandium", 44.955912, 1.84, 1.70, 1.48, 1.16, 1.14, 2.11,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Ti"), 22, 4, 4, "Titanium", 47.867, 1.76, 1.60, 1.36, 1.17, 1.08, 1.87,
              std::vector<int>{-2, -1, 1, 2, 3, 4}),
    SKElement(std::string("V"), 23, 5, 4, "Vanadium", 50.9415, 1.71, 1.53, 1.34, 1.12, 1.06, 1.79,
              std::vector<int>{-3, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("Cr"), 24, 6, 4, "Chromium", 51.9961, 1.66, 1.39, 1.22, 1.11, 1.03, 1.89,
              std::vector<int>{-4, -2, -1, 1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Mn"), 25, 7, 4, "Manganese", 54.939045, 1.61, 1.39, 1.19, 1.05, 1.03, 1.97,
              std::vector<int>{-3, -2, 1, 1, 2, 3, 4, 5, 6, 7}),
    SKElement(std::string("Fe"), 26, 8, 4, "Iron", 55.845, 1.56, 1.32, 1.16, 1.09, 1.02, 1.94,
              std::vector<int>{-4, -2, -1, 1, 2, 3, 4, 5, 6, 7}),
    SKElement(std::string("Co"), 27, 9, 4, "Cobalt", 58.933195, 1.52, 1.26, 1.11, 1.03, 0.96, 1.92,
              std::vector<int>{-3, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("Ni"), 28, 10, 4, "Nickel", 58.6934, 1.49, 1.24, 1.10, 1.01, 1.01, 1.63,
              std::vector<int>{-2, -1, 1, 2, 3, 4}),
    SKElement(std::string("Cu"), 29, 11, 4, "Copper", 63.546, 1.45, 1.32, 1.12, 1.15, 1.2, 1.40,
              std::vector<int>{-2, 1, 2, 3, 4}),
    SKElement(std::string("Zn"), 30, 12, 4, "Zinc", 65.38, 1.42, 1.22, 1.18, 1.20, 0.0, 1.39,
              std::vector<int>{-2, 0, 1, 2}),
    SKElement(std::string("Ga"), 31, 13, 4, "Gallium", 69.723, 1.36, 1.22, 1.24, 1.17, 1.21, 1.87,
              std::vector<int>{-5, -4, -2, -1, 1, 2, 3}),
    SKElement(std::string("Ge"), 32, 14, 4, "Germanium", 72.64, 1.25, 1.20, 1.21, 1.11, 1.14, 2.11,
              std::vector<int>{-4, -3, -2, -1, 0, 1, 2, 3, 4}),
    SKElement(std::string("As"), 33, 15, 4, "Arsenic", 74.9216, 1.14, 1.19, 1.21, 1.14, 1.06, 1.85,
              std::vector<int>{-3, -2, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("Se"), 34, 16, 3, "Selenium", 78.96, 1.03, 1.20, 1.16, 1.07, 1.07, 1.90,
              std::vector<int>{-2, -1, 1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Br"), 35, 17, 4, "Bromine", 79.904, 0.94, 1.20, 1.14, 1.09, 1.10, 1.85,
              std::vector<int>{-1, 1, 3, 4, 5, 7}),
    SKElement(std::string("Kr"), 36, 18, 4, "Krypton", 83.798, 0.88, 1.16, 1.17, 1.21, 1.08, 2.02,
              std::vector<int>{0, 1, 2}),
    SKElement(std::string("Rb"), 37, 1, 5, "Rubidium", 85.4678, 2.65, 2.20, 2.10, 2.02, 0.0, 3.03,
              std::vector<int>{-1, 1}),
    SKElement(std::string("Sr"), 38, 2, 5, "Strontium", 87.62, 2.19, 1.95, 1.85, 1.57, 1.39, 2.49,
              std::vector<int>{1, 2}),
    SKElement(std::string("Y"), 39, 3, 5, "Yttrium", 88.90585, 2.12, 1.90, 1.63, 1.30, 1.24, 2.19,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Zr"), 40, 4, 5, "Zirconium", 91.224, 2.06, 1.75, 1.54, 1.27, 1.21, 1.86,
              std::vector<int>{-2, 1, 2, 3, 4}),
    SKElement(std::string("Nb"), 41, 5, 5, "Niobium", 92.90638, 1.98, 1.64, 1.47, 1.25, 1.16, 2.07,
              std::vector<int>{-3, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("Mo"), 42, 6, 5, "Molybdenum", 95.96, 1.90, 1.54, 1.38, 1.21, 1.13, 2.09,
              std::vector<int>{-4, -2, -1, 1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Tc"), 43, 7, 5, "Technetium", 98, 1.83, 1.47, 1.28, 1.20, 1.10, 2.09,
              std::vector<int>{-3, -1, 1, 2, 3, 4, 5, 6, 7}),
    SKElement(std::string("Ru"), 44, 8, 5, "Ruthenium", 101.07, 1.78, 1.46, 1.25, 1.14, 1.03, 2.07,
              std::vector<int>{-4, -2, 1, 2, 3, 4, 5, 6, 7, 8}),
    SKElement(std::string("Rh"), 45, 9, 5, "Rhodium", 102.59055, 1.73, 1.42, 1.25, 1.10, 1.06, 1.95,
              std::vector<int>{-3, -1, 1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Pd"), 46, 10, 5, "Palladium", 106.42, 1.69, 1.39, 1.20, 1.17, 1.12, 1.63,
              std::vector<int>{0, 1, 2, 3, 4}),
    SKElement(std::string("Ag"), 47, 11, 5, "Silver", 107.8682, 1.65, 1.45, 1.28, 1.39, 1.37, 1.72,
              std::vector<int>{-2, -1, 1, 2, 3}),
    SKElement(std::string("Cd"), 48, 12, 5, "Cadmium", 112.411, 1.61, 1.44, 1.36, 1.44, 0.0, 1.58,
              std::vector<int>{-2, 1, 2}),
    SKElement(std::string("In"), 49, 13, 5, "Indium", 114.818, 1.56, 1.42, 1.42, 1.36, 1.46, 1.93,
              std::vector<int>{-5, -2, -1, 1, 2, 3}),
    SKElement(std::string("Sn"), 50, 14, 5, "Tin", 118.71, 1.45, 1.39, 1.40, 1.30, 1.32, 2.17,
              std::vector<int>{-4, -3, -2, -1, 1, 2, 3, 4}),
    SKElement(std::string("Sb"), 51, 15, 5, "Antimony", 121.76, 1.33, 1.39, 1.40, 1.33, 1.27, 2.06,
              std::vector<int>{-3, -2, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("Te"), 52, 16, 5, "Tellurium", 127.6, 1.23, 1.38, 1.36, 1.28, 1.21, 2.06,
              std::vector<int>{-2, -1, 1, 2, 3, 4, 5, 6}),
    SKElement(std::string("I"), 53, 17, 5, "Iodine", 126.90447, 1.15, 1.39, 1.33, 1.29, 1.25, 1.98,
              std::vector<int>{-1, 1, 3, 4, 5, 6, 7}),
    SKElement(std::string("Xe"), 54, 18, 5, "Xenon", 131.293, 1.08, 1.40, 1.31, 1.35, 1.22, 2.16,
              std::vector<int>{0, 1, 2, 4, 6, 8}),
    SKElement(std::string("Cs"), 55, 1, 6, "Cesium", 132.9054519, 2.98, 2.44, 2.32, 2.09, 0.0, 3.43,
              std::vector<int>{-1, 1}),
    SKElement(std::string("Ba"), 56, 2, 6, "Barium", 137.327, 2.53, 2.15, 1.96, 1.61, 1.49, 2.68,
              std::vector<int>{1, 2}),
    SKElement(std::string("La"), 57, -1, 6, "Lanthanum", 138.90547, 2.26, 2.07, 1.80, 1.39, 1.39, 2.40,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Ce"), 58, -1, 6, "Cerium", 140.116, 2.10, 2.04, 1.63, 1.37, 1.31, 2.35,
              std::vector<int>{1, 2, 3, 4}),
    SKElement(std::string("Pr"), 59, -1, 6, "Praseodymium", 140.90765, 2.47, 2.03, 1.76, 1.38, 1.28, 2.39,
              std::vector<int>{2, 3, 4, 5}),
    SKElement(std::string("Nd"), 60, -1, 6, "Neodymium", 144.242, 2.06, 2.01, 1.74, 1.37, 0.0, 2.29,
              std::vector<int>{2, 3, 4}),
    SKElement(std::string("Pm"), 61, -1, 6, "Promethium", 145, 2.05, 1.99, 1.73, 1.35, 0.0, 2.36,
              std::vector<int>{2, 3}),
    SKElement(std::string("Sm"), 62, -1, 6, "Samarium", 150.36, 2.38, 1.98, 1.72, 1.34, 0.0, 2.29,
              std::vector<int>{1, 2, 3, 4}),
    SKElement(std::string("Eu"), 63, -1, 6, "Europium", 151.964, 2.31, 1.98, 1.68, 1.34, 0.0, 2.33,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Gd"), 64, -1, 6, "Gadolinium", 157.25, 2.33, 1.96, 1.68, 1.35, 1.32, 2.37,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Tb"), 65, -1, 6, "Terbium", 158.92535, 2.25, 1.94, 1.68, 1.35, 0.0, 2.21,
              std::vector<int>{1, 2, 3, 4}),
    SKElement(std::string("Dy"), 66, -1, 6, "Dysprosium", 162.5, 2.28, 1.92, 1.67, 1.33, 0.0, 2.29,
              std::vector<int>{1, 2, 3, 4}),
    SKElement(std::string("Ho"), 67, -1, 6, "Holmium", 164.93032, 2.26, 1.92, 1.66, 1.33, 0.0, 2.16,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Er"), 68, -1, 6, "Erbium", 167.259, 2.26, 1.89, 1.65, 1.33, 0.0, 2.35,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Tm"), 69, -1, 6, "Thulium", 168.93421, 2.22, 1.90, 1.64, 1.31, 0.0, 2.27,
              std::vector<int>{2, 3}),
    SKElement(std::string("Yb"), 70, -1, 6, "Ytterbium", 173.054, 2.22, 1.87, 1.70, 1.29, 0.0, 2.42,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Lu"), 71, 3, 6, "Lutetium", 174.9668, 2.17, 1.75, 1.62, 1.31, 1.31, 2.21,
              std::vector<int>{1, 2, 3}),
    SKElement(std::string("Hf"), 72, 4, 6, "Hafnium", 178.49, 2.08, 1.87, 1.52, 1.28, 1.22, 2.12,
              std::vector<int>{-2, 1, 2, 3, 4}),
    SKElement(std::string("Ta"), 73, 5, 6, "Tantalum", 180.94788, 2.00, 1.70, 1.46, 1.26, 1.19, 2.17,
              std::vector<int>{-3, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("W"), 74, 6, 6, "Tungsten", 183.84, 1.93, 1.62, 1.37, 1.20, 1.15, 2.10,
              std::vector<int>{-4, -2, -1, 0, 1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Re"), 75, 7, 6, "Rhenium", 186.207, 1.88, 1.51, 1.31, 1.19, 1.10, 2.17,
              std::vector<int>{-3, -1, 0, 1, 2, 3, 4, 5, 6, 7}),
    SKElement(std::string("Os"), 76, 8, 6, "Osmium", 190.23, 1.85, 1.44, 1.29, 1.16, 1.09, 2.16,
              std::vector<int>{-4, -2, 0, 1, 2, 3, 4, 5, 6, 7, 8}),
    SKElement(std::string("Ir"), 77, 9, 6, "Iridium", 192.217, 1.90, 1.41, 1.22, 1.15, 1.07, 2.02,
              std::vector<int>{-3, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9}),
    SKElement(std::string("Pt"), 78, 10, 6, "Platinum", 195.084, 1.77, 1.36, 1.23, 1.12, 1.10, 1.75,
              std::vector<int>{-3, -2, -1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Au"), 79, 11, 6, "Gold", 196.966569, 1.74, 1.36, 1.24, 1.21, 1.23, 1.66,
              std::vector<int>{-3, -2, -1, 1, 2, 3, 5}),
    SKElement(std::string("Hg"), 80, 12, 6, "Mercury", 200.59, 1.71, 1.32, 1.33, 1.42, 0.0, 1.55,
              std::vector<int>{-2, 1, 2}),
    SKElement(std::string("Tl"), 81, 13, 6, "Thallium", 204.3833, 1.56, 1.45, 1.44, 1.42, 1.50, 1.96,
              std::vector<int>{-5, -2, -1, 1, 2, 3}),
    SKElement(std::string("Pb"), 82, 14, 6, "Lead", 207.2, 1.54, 1.46, 1.44, 1.35, 1.37, 2.02,
              std::vector<int>{-4, -2, -1, 2, 3, 4}),
    SKElement(std::string("Bi"), 83, 15, 6, "Bismuth", 208.9804, 1.43, 1.48, 1.51, 1.41, 1.35, 2.07,
              std::vector<int>{-3, -2, -1, 1, 2, 3, 4, 5}),
    SKElement(std::string("Po"), 84, 16, 6, "Polonium", 210, 1.35, 1.40, 1.45, 1.35, 1.29, 1.97,
              std::vector<int>{-2, 2, 4, 5, 6}),
    SKElement(std::string("At"), 85, 17, 6, "Astatine", 210.8, 1.27, 1.50, 1.47, 1.38, 1.38, 2.02,
              std::vector<int>{-1, 1, 3, 5, 7}),
    SKElement(std::string("Rn"), 86, 18, 6, "Radon", 222, 1.20, 1.50, 1.42, 1.45, 1.33, 2.20,
              std::vector<int>{0, 2, 6}),
    SKElement(std::string("Fr"), 87, 1, 7, "Francium", 223, 0.0, 2.60, 2.23, 2.18, 0.0, 3.48, std::vector<int>{1}),
    SKElement(std::string("Ra"), 88, 2, 7, "Radium", 226, 0.0, 2.21, 2.01, 1.73, 1.59, 2.83, std::vector<int>{2}),
    SKElement(std::string("Ac"), 89, -1, 7, "Actinium", 227, 0.0, 2.15, 1.86, 1.53, 1.40, 2.60, std::vector<int>{2, 3}),
    SKElement(std::string("Th"), 90, -1, 7, "Thorium", 232.03806, 0.0, 2.06, 1.75, 1.43, 1.36, 2.37,
              std::vector<int>{1, 2, 3, 4}),
    SKElement(std::string("Pa"), 91, -1, 7, "Protactinium", 231.03588, 1.63, 2.00, 1.69, 1.38, 1.29, 2.43,
              std::vector<int>{2, 3, 4, 5}),
    SKElement(std::string("U"), 92, -1, 7, "Uranium", 238.02891, 1.56, 1.96, 1.70, 1.34, 1.18, 2.40,
              std::vector<int>{1, 2, 3, 4, 5, 6}),
    SKElement(std::string("Np"), 93, -1, 7, "Neptunium", 237, 1.55, 1.90, 1.71, 1.36, 1.16, 2.21,
              std::vector<int>{2, 3, 4, 5, 6, 7}),
    SKElement(std::string("Pu"), 94, -1, 7, "Plutonium", 244, 1.59, 1.87, 1.72, 1.35, 0.0, 2.43,
              std::vector<int>{1, 2, 3, 4, 5, 6, 7, 8}),
    SKElement(std::string("Am"), 95, -1, 7, "Americium", 243, 1.73, 1.80, 1.66, 1.35, 0.0, 2.44,
              std::vector<int>{2, 3, 4, 5, 6, 7, 8}),
    SKElement(std::string("Cm"), 96, -1, 7, "Curium", 247, 1.74, 1.69, 1.66, 1.36, 0.0, 2.45,
              std::vector<int>{2, 3, 4, 6}),
    SKElement(std::string("Bk"), 97, -1, 7, "Berkelium", 247, 1.7, 0.0, 1.68, 1.39, 0.0, 2.44,
              std::vector<int>{2, 3, 4}),
    SKElement(std::string("Cf"), 98, -1, 7, "Californium", 251, 0.0, 0.0, 1.68, 1.40, 0.0, 2.45,
              std::vector<int>{2, 3, 4}),
    SKElement(std::string("Es"), 99, -1, 7, "Einsteinium", 252, 0.0, 0.0, 1.65, 1.40, 0.0, 2.45,
              std::vector<int>{2, 3, 4}),
    SKElement(std::string("Fm"), 100, -1, 7, "Fermium", 257, 0.0, 0.0, 1.67, 0.0, 0.0, 0.0, std::vector<int>{2, 3}),
    SKElement(std::string("Md"), 101, -1, 7, "Mendelevium", 258, 0.0, 0.0, 1.73, 1.39, 0.0, 0.0,
              std::vector<int>{2, 3}),
    SKElement(std::string("No"), 102, -1, 7, "Nobelium", 259, 0.0, 0.0, 1.76, 0.0, 0.0, 0.0, std::vector<int>{2, 3}),
    SKElement(std::string("Lr"), 103, 3, 7, "Lawrencium", 262, 0.0, 0.0, 1.61, 1.41, 0.0, 0.0, std::vector<int>{3}),
    SKElement(std::string("Rf"), 104, 4, 7, "Rutherfordium", 261, 0.0, 0.0, 1.57, 1.40, 1.31, 0.0,
              std::vector<int>{2, 3, 4}),
    SKElement(std::string("Db"), 105, 5, 7, "Dubnium", 268, 1.39, 1.49, 1.49, 1.36, 1.26, 0.0,
              std::vector<int>{3, 4, 5}),
    SKElement(std::string("Sg"), 106, 6, 7, "Seaborgium", 269, 1.32, 1.43, 1.43, 1.28, 1.21, 0.0,
              std::vector<int>{3, 4, 5, 6}),
    SKElement(std::string("Bh"), 107, 7, 7, "Bohrium", 270, 1.28, 1.41, 1.41, 1.28, 1.19, 0.0,
              std::vector<int>{3, 4, 5, 7}),
    SKElement(std::string("Hs"), 108, 8, 7, "Hassium", 269, 1.26, 1.34, 1.34, 1.25, 1.18, 0.0,
              std::vector<int>{2, 3, 4, 5, 6, 8}),
    SKElement(std::string("Mt"), 109, 9, 7, "Meitnerium", 278, 1.28, 1.29, 1.29, 1.25, 1.13, 0.0,
              std::vector<int>{1, 3, 4, 6, 8, 9}),
    SKElement(std::string("Ds"), 110, 10, 7, "Darmstadtium", 281, 1.32, 1.28, 1.28, 1.16, 1.12, 0.0,
              std::vector<int>{0, 2, 4, 6, 8}),
    SKElement(std::string("Rg"), 111, 11, 7, "Roentgenium", 281, 1.38, 1.21, 1.21, 1.16, 1.18, 0.0,
              std::vector<int>{-1, 1, 3, 5}),
    SKElement(std::string("Cn"), 112, 12, 7, "Copernicium", 285, 1.47, 1.22, 1.22, 1.37, 1.30, 0.0,
              std::vector<int>{0, 1, 2}),
    SKElement(std::string("Nh"), 113, 13, 7, "Nihonium", 286, 1.70, 1.76, 1.36, 0.0, 0.0, 0.0,
              std::vector<int>{-1, 1, 3, 5}),
    SKElement(std::string("Fl"), 114, 14, 7, "Flerovium", 289, 1.80, 1.74, 1.43, 0.0, 0.0, 0.0,
              std::vector<int>{0, 1, 2, 4, 6}),
    SKElement(std::string("Mc"), 115, 15, 7, "Moscovium", 288, 1.87, 1.57, 1.62, 0.0, 0.0, 0.0, std::vector<int>{1, 3}),
    SKElement(std::string("Lv"), 116, 16, 7, "Livermorium", 293, 1.83, 1.64, 1.75, 0.0, 0.0, 0.0,
              std::vector<int>{-2, 2, 4}),
    SKElement(std::string("Ts"), 117, 17, 7, "Tennessine", 294, 1.38, 1.56, 1.65, 0.0, 0.0, 0.0,
              std::vector<int>{-1, 1, 3, 5}),
    SKElement(std::string("Og"), 118, 18, 7, "Oganesson", 294, 1.52, 1.57, 1.57, 0.0, 0.0, 0.0,
              std::vector<int>{-1, 0, 1, 2, 4, 6})};

std::map<std::string, std::size_t, PredefinedElements::InsensitiveCompare> PredefinedElements::atomicNumberData = {
    {std::string("H"), 1},
    {std::string("He"), 2},
    {std::string("Li"), 3},
    {std::string("Be"), 4},
    {std::string("B"), 5},
    {std::string("C"), 6},
    {std::string("N"), 7},
    {std::string("O"), 8},
    {std::string("F"), 9},
    {std::string("Ne"), 10},
    {std::string("Na"), 11},
    {std::string("Mg"), 12},
    {std::string("Al"), 13},
    {std::string("Si"), 14},
    {std::string("P"), 15},
    {
        std::string("S"),
        16,
    },
    {std::string("Cl"), 17},
    {std::string("Ar"), 18},
    {std::string("K"), 19},
    {std::string("Ca"), 20},
    {std::string("Sc"), 21},
    {std::string("Ti"), 22},
    {std::string("V"), 23},
    {std::string("Cr"), 24},
    {std::string("Mn"), 25},
    {std::string("Fe"), 26},
    {std::string("Co"), 27},
    {std::string("Ni"), 28},
    {std::string("Cu"), 29},
    {std::string("Zn"), 30},
    {std::string("Ga"), 31},
    {std::string("Ge"), 32},
    {std::string("As"), 33},
    {
        std::string("Se"),
        34,
    },
    {std::string("Br"), 35},
    {std::string("Kr"), 36},
    {std::string("Rb"), 37},
    {std::string("Sr"), 38},
    {std::string("Y"), 39},
    {std::string("Zr"), 40},
    {std::string("Nb"), 41},
    {std::string("Mo"), 42},
    {std::string("Tc"), 43},
    {std::string("Ru"), 44},
    {std::string("Rh"), 45},
    {std::string("Pd"), 46},
    {std::string("Ag"), 47},
    {std::string("Cd"), 48},
    {std::string("In"), 49},
    {std::string("Sn"), 50},
    {std::string("Sb"), 51},
    {std::string("Te"), 52},
    {std::string("I"), 53},
    {std::string("Xe"), 54},
    {std::string("Cs"), 55},
    {std::string("Ba"), 56},
    {std::string("La"), 57},
    {std::string("Ce"), 58},
    {std::string("Pr"), 59},
    {std::string("Nd"), 60},
    {std::string("Pm"), 61},
    {std::string("Sm"), 62},
    {std::string("Eu"), 63},
    {std::string("Gd"), 64},
    {std::string("Tb"), 65},
    {std::string("Dy"), 66},
    {std::string("Ho"), 67},
    {std::string("Er"), 68},
    {std::string("Tm"), 69},
    {std::string("Yb"), 70},
    {std::string("Lu"), 71},
    {std::string("Hf"), 72},
    {std::string("Ta"), 73},
    {std::string("W"), 74},
    {std::string("Re"), 75},
    {std::string("Os"), 76},
    {std::string("Ir"), 77},
    {std::string("Pt"), 78},
    {std::string("Au"), 79},
    {std::string("Hg"), 80},
    {std::string("Tl"), 81},
    {std::string("Pb"), 82},
    {std::string("Bi"), 83},
    {std::string("Po"), 84},
    {std::string("At"), 85},
    {std::string("Rn"), 86},
    {std::string("Fr"), 87},
    {std::string("Ra"), 88},
    {std::string("Ac"), 89},
    {std::string("Th"), 90},
    {std::string("Pa"), 91},
    {std::string("U"), 92},
    {std::string("Np"), 93},
    {std::string("Pu"), 94},
    {std::string("Am"), 95},
    {std::string("Cm"), 96},
    {std::string("Bk"), 97},
    {std::string("Cf"), 98},
    {std::string("Es"), 99},
    {std::string("Fm"), 100},
    {std::string("Md"), 101},
    {std::string("No"), 102},
    {std::string("Lr"), 103},
    {std::string("Rf"), 104},
    {std::string("Db"), 105},
    {std::string("Sg"), 106},
    {std::string("Bh"), 107},
    {std::string("Hs"), 108},
    {std::string("Mt"), 109},
    {std::string("Ds"), 110},
    {std::string("Rg"), 111},
    {std::string("Cn"), 112},
    {std::string("Nh"), 113},
    {std::string("Fl("), 114},
    {std::string("Mc"), 115},
    {std::string("Lv"), 116},
    {std::string("Ts"), 117},
    {std::string("Og"), 118}};

std::set<std::string> PredefinedElements::residueDefinitions = {
    std::string("ALA"), std::string("ARG"), std::string("ASN"), std::string("ASP"), std::string("CYS"),
    std::string("GLN"), std::string("GLU"), std::string("GLY"), std::string("HIS"), std::string("HOH"),
    std::string("ILE"), std::string("LEU"), std::string("LYS"), std::string("MET"), std::string("PHE"),
    std::string("PRO"), std::string("SER"), std::string("THR"), std::string("TRP"), std::string("TYR"),
    std::string("VAL")};

std::map<std::string, std::string> PredefinedElements::residueDefinitionsElement = {
    {std::string("ALA+C"), "C"},    {std::string("ALA+CA"), "C"},   {std::string("ALA+CB"), "C"},
    {std::string("ALA+N"), "N"},    {std::string("ALA+O"), "O"},    {std::string("ALA+OXT"), "O"},
    {std::string("ALA+H"), "H"},    {std::string("ALA+HA"), "H"},   {std::string("ALA+HB1"), "H"},
    {std::string("ALA+HB2"), "H"},  {std::string("ALA+HB3"), "H"},

    {std::string("ARG+C"), "C"},    {std::string("ARG+CA"), "C"},   {std::string("ARG+CB"), "C"},
    {std::string("ARG+CD"), "C"},   {std::string("ARG+CG"), "C"},   {std::string("ARG+CZ"), "C"},
    {std::string("ARG+N"), "N"},    {std::string("ARG+NE"), "N"},   {std::string("ARG+NH1"), "N"},
    {std::string("ARG+NH2"), "N"},  {std::string("ARG+O"), "O"},    {std::string("ARG+OXT"), "O"},
    {std::string("ARG+H"), "H"},    {std::string("ARG+HA"), "H"},   {std::string("ARG+HB2"), "H"},
    {std::string("ARG+HB3"), "H"},  {std::string("ARG+HD2"), "H"},  {std::string("ARG+HD3"), "H"},
    {std::string("ARG+HE"), "H"},   {std::string("ARG+HG2"), "H"},  {std::string("ARG+HG3"), "H"},
    {std::string("ARG+HH11"), "H"}, {std::string("ARG+HH12"), "H"}, {std::string("ARG+HH21"), "H"},
    {std::string("ARG+HH22"), "H"},

    {std::string("ASN+C"), "C"},    {std::string("ASN+CA"), "C"},   {std::string("ASN+CB"), "C"},
    {std::string("ASN+CG"), "C"},   {std::string("ASN+N"), "N"},    {std::string("ASN+ND2"), "N"},
    {std::string("ASN+O"), "O"},    {std::string("ASN+OD1"), "O"},  {std::string("ASN+OXT"), "O"},
    {std::string("ASN+H"), "H"},    {std::string("ASN+HA"), "H"},   {std::string("ASN+HB2"), "H"},
    {std::string("ASN+HB3"), "H"},  {std::string("ASN+HD21"), "H"}, {std::string("ASN+HD22"), "H"},

    {std::string("ASP+C"), "C"},    {std::string("ASP+CA"), "C"},   {std::string("ASP+CB"), "C"},
    {std::string("ASP+CG"), "C"},   {std::string("ASP+N"), "N"},    {std::string("ASP+O"), "O"},
    {std::string("ASP+OD1"), "O"},  {std::string("ASP+OD2"), "O"},  {std::string("ASP+OXT"), "O"},
    {std::string("ASP+H"), "H"},    {std::string("ASP+HA"), "H"},   {std::string("ASP+HB2"), "H"},
    {std::string("ASP+HB3"), "H"},

    {std::string("CYS+C"), "C"},    {std::string("CYS+CA"), "C"},   {std::string("CYS+CB"), "C"},
    {std::string("CYS+N"), "N"},    {std::string("CYS+O"), "O"},    {std::string("CYS+SG"), "S"},
    {std::string("CYS+OXT"), "O"},  {std::string("CYS+H"), "H"},    {std::string("CYS+HA"), "H"},
    {std::string("CYS+HB2"), "H"},  {std::string("CYS+HB3"), "H"},

    {std::string("GLN+C"), "C"},    {std::string("GLN+CA"), "C"},   {std::string("GLN+CB"), "C"},
    {std::string("GLN+CD"), "C"},   {std::string("GLN+CG"), "C"},   {std::string("GLN+N"), "N"},
    {std::string("GLN+NE2"), "N"},  {std::string("GLN+O"), "O"},    {std::string("GLN+OE1"), "O"},
    {std::string("GLN+OXT"), "O"},  {std::string("GLN+H"), "H"},    {std::string("GLN+HA"), "H"},
    {std::string("GLN+HB2"), "H"},  {std::string("GLN+HB3"), "H"},  {std::string("GLN+HG2"), "H"},
    {std::string("GLN+HG3"), "H"},  {std::string("GLN+HE21"), "H"}, {std::string("GLN+HE22"), "H"},

    {std::string("GLU+C"), "C"},    {std::string("GLU+CA"), "C"},   {std::string("GLU+CB"), "C"},
    {std::string("GLU+CD"), "C"},   {std::string("GLU+CG"), "C"},   {std::string("GLU+N"), "N"},
    {std::string("GLU+O"), "O"},    {std::string("GLU+OE1"), "O"},  {std::string("GLU+OE2"), "O"},
    {std::string("GLU+OXT"), "O"},  {std::string("GLU+H"), "H"},    {std::string("GLU+HA"), "H"},
    {std::string("GLU+HB2"), "H"},  {std::string("GLU+HB3"), "H"},  {std::string("GLU+HG2"), "H"},
    {std::string("GLU+HG3"), "H"},

    {std::string("GLY+C"), "C"},    {std::string("GLY+CA"), "C"},   {std::string("GLY+N"), "N"},
    {std::string("GLY+O"), "O"},    {std::string("GLY+OXT"), "O"},  {std::string("GLY+H"), "H"},
    {std::string("GLY+HA"), "H"},   {std::string("GLY+HA2"), "H"},  {std::string("GLY+HA3"), "H"},
    {std::string("GLY+HB2"), "H"},  {std::string("GLY+HB3"), "H"},  {std::string("GLY+HG2"), "H"},
    {std::string("GLY+HG3"), "H"},

    {std::string("HIS+C"), "C"},    {std::string("HIS+CA"), "C"},   {std::string("HIS+CB"), "C"},
    {std::string("HIS+CD2"), "C"},  {std::string("HIS+CE1"), "C"},  {std::string("HIS+CG"), "C"},
    {std::string("HIS+N"), "N"},    {std::string("HIS+ND1"), "N"},  {std::string("HIS+NE2"), "N"},
    {std::string("HIS+O"), "O"},    {std::string("HIS+OXT"), "O"},  {std::string("HIS+H"), "H"},
    {std::string("HIS+HA"), "H"},   {std::string("HIS+HB2"), "H"},  {std::string("HIS+HB3"), "H"},
    {std::string("HIS+HD1"), "H"},  {std::string("HIS+HD2"), "H"},  {std::string("HIS+HE1"), "H"},

    {std::string("HOH+O"), "C"},    {std::string("HOH+H"), "H"},

    {std::string("ILE+C"), "C"},    {std::string("ILE+CA"), "C"},   {std::string("ILE+CB"), "C"},
    {std::string("ILE+CD1"), "C"},  {std::string("ILE+CG1"), "C"},  {std::string("ILE+CG2"), "C"},
    {std::string("ILE+N"), "N"},    {std::string("ILE+O"), "O"},    {std::string("ILE+OXT"), "O"},
    {std::string("ILE+H"), "H"},    {std::string("ILE+HA"), "H"},   {std::string("ILE+HB"), "H"},
    {std::string("ILE+HG12"), "H"}, {std::string("ILE+HG13"), "H"}, {std::string("ILE+HG21"), "H"},
    {std::string("ILE+HG22"), "H"}, {std::string("ILE+HG23"), "H"}, {std::string("ILE+HD11"), "H"},
    {std::string("ILE+HD12"), "H"}, {std::string("ILE+HD13"), "H"},

    {std::string("LEU+C"), "C"},    {std::string("LEU+CA"), "C"},   {std::string("LEU+CB"), "C"},
    {std::string("LEU+CD1"), "C"},  {std::string("LEU+CD2"), "C"},  {std::string("LEU+CG"), "C"},
    {std::string("LEU+N"), "N"},    {std::string("LEU+O"), "O"},    {std::string("LEU+H"), "H"},
    {std::string("LEU+HA"), "H"},   {std::string("LEU+HB2"), "H"},  {std::string("LEU+HB3"), "H"},
    {std::string("LEU+HD11"), "H"}, {std::string("LEU+HD12"), "H"}, {std::string("LEU+HD13"), "H"},
    {std::string("LEU+HD21"), "H"}, {std::string("LEU+HD22"), "H"}, {std::string("LEU+HD23"), "H"},
    {std::string("LEU+HG"), "H"},

    {std::string("LYS+C"), "C"},    {std::string("LYS+CA"), "C"},   {std::string("LYS+CB"), "C"},
    {std::string("LYS+CD"), "C"},   {std::string("LYS+CE"), "C"},   {std::string("LYS+CG"), "C"},
    {std::string("LYS+N"), "N"},    {std::string("LYS+NZ"), "N"},   {std::string("LYS+O"), "O"},
    {std::string("LYS+OXT"), "O"},  {std::string("LYS+H"), "H"},    {std::string("LYS+HA"), "H"},
    {std::string("LYS+HB2"), "H"},  {std::string("LYS+HB3"), "H"},  {std::string("LYS+HG2"), "H"},
    {std::string("LYS+HG3"), "H"},  {std::string("LYS+HD2"), "H"},  {std::string("LYS+HD3"), "H"},
    {std::string("LYS+HE2"), "H"},  {std::string("LYS+HE3"), "H"},

    {std::string("MET+C"), "C"},    {std::string("MET+CA"), "C"},   {std::string("MET+CB"), "C"},
    {std::string("MET+CE"), "C"},   {std::string("MET+CG"), "C"},   {std::string("MET+N"), "N"},
    {std::string("MET+O"), "O"},    {std::string("MET+SD"), "S"},   {std::string("MET+OXT"), "O"},
    {std::string("MET+H"), "H"},

    {std::string("PHE+C"), "C"},    {std::string("PHE+CA"), "C"},   {std::string("PHE+CB"), "C"},
    {std::string("PHE+CD1"), "C"},  {std::string("PHE+CD2"), "C"},  {std::string("PHE+CE1"), "C"},
    {std::string("PHE+CE2"), "C"},  {std::string("PHE+CG"), "C"},   {std::string("PHE+CZ"), "C"},
    {std::string("PHE+N"), "N"},    {std::string("PHE+O"), "O"},    {std::string("PHE+OXT"), "O"},
    {std::string("PHE+H"), "H"},    {std::string("PHE+HA"), "H"},   {std::string("PHE+HB2"), "H"},
    {std::string("PHE+HB3"), "H"},  {std::string("PHE+HD1"), "H"},  {std::string("PHE+HD2"), "H"},
    {std::string("PHE+HE1"), "H"},  {std::string("PHE+HE2"), "H"},  {std::string("PHE+HZ"), "H"},

    {std::string("PRO+C"), "C"},    {std::string("PRO+CA"), "C"},   {std::string("PRO+CB"), "C"},
    {std::string("PRO+CD"), "C"},   {std::string("PRO+CG"), "C"},   {std::string("PRO+N"), "N"},
    {std::string("PRO+O"), "O"},    {std::string("PRO+OXT"), "O"},  {std::string("PRO+H"), "H"},
    {std::string("PRO+HA"), "H"},   {std::string("PRO+HB2"), "H"},  {std::string("PRO+HB3"), "H"},
    {std::string("PRO+HD2"), "H"},  {std::string("PRO+HD3"), "H"},  {std::string("PRO+HG2"), "H"},
    {std::string("PRO+HG3"), "H"},

    {std::string("SER+C"), "C"},    {std::string("SER+CA"), "C"},   {std::string("SER+CB"), "C"},
    {std::string("SER+N"), "N"},    {std::string("SER+O"), "O"},    {std::string("SER+OG"), "O"},
    {std::string("SER+OXT"), "O"},  {std::string("SER+H"), "H"},    {std::string("SER+HA"), "H"},
    {std::string("SER+HB2"), "H"},  {std::string("SER+HB3"), "H"},

    {std::string("THR+C"), "C"},    {std::string("THR+CA"), "C"},   {std::string("THR+CB"), "C"},
    {std::string("THR+CG2"), "C"},  {std::string("THR+N"), "N"},    {std::string("THR+O"), "O"},
    {std::string("THR+OG1"), "O"},  {std::string("THR+OXT"), "O"},  {std::string("THR+H"), "H"},
    {std::string("THR+HA"), "H"},   {std::string("THR+HB"), "H"},   {std::string("THR+HG1"), "H"},
    {std::string("THR+HG21"), "H"}, {std::string("THR+HG22"), "H"}, {std::string("THR+HG23"), "H"},
    {std::string("THR+HH2"), "H"},

    {std::string("TRP+C"), "C"},    {std::string("TRP+CA"), "C"},   {std::string("TRP+CB"), "C"},
    {std::string("TRP+CD1"), "C"},  {std::string("TRP+CD2"), "C"},  {std::string("TRP+CE2"), "C"},
    {std::string("TRP+CE3"), "C"},  {std::string("TRP+CG"), "C"},   {std::string("TRP+CH2"), "C"},
    {std::string("TRP+CZ2"), "C"},  {std::string("TRP+CZ3"), "C"},  {std::string("TRP+N"), "N"},
    {std::string("TRP+NE1"), "N"},  {std::string("TRP+O"), "O"},    {std::string("TRP+OXT"), "O"},
    {std::string("TRP+H"), "H"},    {std::string("TRP+HA"), "H"},   {std::string("TRP+HB2"), "H"},
    {std::string("TRP+HB3"), "H"},  {std::string("TRP+HD1"), "H"},  {std::string("TRP+HE1"), "H"},
    {std::string("TRP+HE3"), "H"},  {std::string("TRP+HZ2"), "H"},  {std::string("TRP+HZ3"), "H"},
    {std::string("TRP+HH2"), "H"},

    {std::string("TYR+C"), "C"},    {std::string("TYR+CA"), "C"},   {std::string("TYR+CB"), "C"},
    {std::string("TYR+CD1"), "C"},  {std::string("TYR+CD2"), "C"},  {std::string("TYR+CE1"), "C"},
    {std::string("TYR+CE2"), "C"},  {std::string("TYR+CG"), "C"},   {std::string("TYR+CZ"), "C"},
    {std::string("TYR+N"), "N"},    {std::string("TYR+O"), "O"},    {std::string("TYR+OH"), "O"},
    {std::string("TYR+OXT"), "O"},  {std::string("TYR+H"), "H"},    {std::string("TYR+HA"), "H"},
    {std::string("TYR+HB2"), "H"},  {std::string("TYR+HB3"), "H"},  {std::string("TYR+HD1"), "H"},
    {std::string("TYR+HD2"), "H"},  {std::string("TYR+HE1"), "H"},  {std::string("TYR+HE2"), "H"},

    {std::string("VAL+C"), "C"},    {std::string("VAL+CA"), "C"},   {std::string("VAL+CB"), "C"},
    {std::string("VAL+CG1"), "C"},  {std::string("VAL+CG2"), "C"},  {std::string("VAL+N"), "N"},
    {std::string("VAL+O"), "O"},    {std::string("VAL+OXT"), "O"},  {std::string("VAL+H"), "H"},
    {std::string("VAL+HA"), "H"},   {std::string("VAL+HB"), "H"},   {std::string("VAL+HG11"), "H"},
    {std::string("VAL+HG12"), "H"}, {std::string("VAL+HG13"), "H"}, {std::string("VAL+HG21"), "H"},
    {std::string("VAL+HG22"), "H"}, {std::string("VAL+HG23"), "H"}};

std::map<std::string, std::string> PredefinedElements::residueDefinitionsType = {
    {std::string("ALA+C"), "C"},      {std::string("ALA+CA"), "CH1E"},  {std::string("ALA+CB"), "CH3E"},
    {std::string("ALA+N"), "NH1"},    {std::string("ALA+O"), "O"},      {std::string("ALA+OXT"), "O"},
    {std::string("ALA+H"), "H"},      {std::string("ALA+HA"), "H"},     {std::string("ALA+HB1"), "H"},
    {std::string("ALA+HB2"), "H"},    {std::string("ALA+HB3"), "H"},

    {std::string("ARG+C"), "C"},      {std::string("ARG+CA"), "CH1E"},  {std::string("ARG+CB"), "CH2E"},
    {std::string("ARG+CD"), "CH2E"},  {std::string("ARG+CG"), "CH2E"},  {std::string("ARG+CZ"), "CH0"},
    {std::string("ARG+N"), "NH1"},    {std::string("ARG+NE"), "NH1S"},  {std::string("ARG+NH1"), "NC2"},
    {std::string("ARG+NH2"), "NC2"},  {std::string("ARG+O"), "O"},      {std::string("ARG+OXT"), "O"},
    {std::string("ARG+H"), "H"},      {std::string("ARG+HA"), "H"},     {std::string("ARG+HB2"), "H"},
    {std::string("ARG+HB3"), "H"},    {std::string("ARG+HD2"), "H"},    {std::string("ARG+HD3"), "H"},
    {std::string("ARG+HE"), "H"},     {std::string("ARG+HG2"), "H"},    {std::string("ARG+HG3"), "H"},
    {std::string("ARG+HH11"), "H"},   {std::string("ARG+HH12"), "H"},   {std::string("ARG+HH21"), "H"},
    {std::string("ARG+HH22"), "H"},

    {std::string("ASN+C"), "C"},      {std::string("ASN+CA"), "CH1E"},  {std::string("ASN+CB"), "CH2E"},
    {std::string("ASN+CG"), "CH0"},   {std::string("ASN+N"), "NH1"},    {std::string("ASN+ND2"), "NH2"},
    {std::string("ASN+O"), "O"},      {std::string("ASN+OD1"), "OS"},   {std::string("ASN+OXT"), "O"},
    {std::string("ASN+H"), "H"},      {std::string("ASN+HA"), "H"},     {std::string("ASN+HB2"), "H"},
    {std::string("ASN+HB3"), "H"},    {std::string("ASN+HD21"), "H"},   {std::string("ASN+HD22"), "H"},

    {std::string("ASP+C"), "C"},      {std::string("ASP+CA"), "CH1E"},  {std::string("ASP+CB"), "CH2E"},
    {std::string("ASP+CG"), "CH0"},   {std::string("ASP+N"), "NH1"},    {std::string("ASP+O"), "O"},
    {std::string("ASP+OD1"), "OC"},   {std::string("ASP+OD2"), "OC"},   {std::string("ASP+OXT"), "O"},
    {std::string("ASP+H"), "H"},      {std::string("ASP+HA"), "H"},     {std::string("ASP+HB2"), "H"},
    {std::string("ASP+HB3"), "H"},

    {std::string("CYS+C"), "C"},      {std::string("CYS+CA"), "CH1E"},  {std::string("CYS+CB"), "CH2E"},
    {std::string("CYS+N"), "NH1"},    {std::string("CYS+O"), "O"},      {std::string("CYS+SG"), "SH1E"},
    {std::string("CYS+OXT"), "O"},    {std::string("CYS+H"), "H"},      {std::string("CYS+HA"), "H"},
    {std::string("CYS+HB2"), "H"},    {std::string("CYS+HB3"), "H"},

    {std::string("GLN+C"), "C"},      {std::string("GLN+CA"), "CH1E"},  {std::string("GLN+CB"), "CH2E"},
    {std::string("GLN+CD"), "CH0"},   {std::string("GLN+CG"), "CH2E"},  {std::string("GLN+N"), "NH1"},
    {std::string("GLN+NE2"), "NH2"},  {std::string("GLN+O"), "O"},      {std::string("GLN+OE1"), "OS"},
    {std::string("GLN+OXT"), "O"},    {std::string("GLN+H"), "H"},      {std::string("GLN+HA"), "H"},
    {std::string("GLN+HB2"), "H"},    {std::string("GLN+HB3"), "H"},    {std::string("GLN+HG2"), "H"},
    {std::string("GLN+HG3"), "H"},    {std::string("GLN+HE21"), "H"},   {std::string("GLN+HE22"), "H"},

    {std::string("GLU+C"), "C"},      {std::string("GLU+CA"), "CH1E"},  {std::string("GLU+CB"), "CH2E"},
    {std::string("GLU+CD"), "CH0"},   {std::string("GLU+CG"), "CH2E"},  {std::string("GLU+N"), "NH1"},
    {std::string("GLU+O"), "O"},      {std::string("GLU+OE1"), "OC"},   {std::string("GLU+OE2"), "OC"},
    {std::string("GLU+OXT"), "O"},    {std::string("GLU+H"), "H"},      {std::string("GLU+HA"), "H"},
    {std::string("GLU+HB2"), "H"},    {std::string("GLU+HB3"), "H"},    {std::string("GLU+HG2"), "H"},
    {std::string("GLU+HG3"), "H"},

    {std::string("GLY+C"), "C"},      {std::string("GLY+CA"), "CH2G"},  {std::string("GLY+N"), "NH1"},
    {std::string("GLY+O"), "O"},      {std::string("GLY+OXT"), "O"},    {std::string("GLY+H"), "H"},
    {std::string("GLY+HA"), "H"},     {std::string("GLY+HA2"), "H"},    {std::string("GLY+HA3"), "H"},
    {std::string("GLY+HB2"), "H"},    {std::string("GLY+HB3"), "H"},    {std::string("GLY+HG2"), "H"},
    {std::string("GLY+HG3"), "H"},

    {std::string("HIS+C"), "C"},      {std::string("HIS+CA"), "CH1E"},  {std::string("HIS+CB"), "CH2E"},
    {std::string("HIS+CD2"), "CR1H"}, {std::string("HIS+CE1"), "CRHH"}, {std::string("HIS+CG"), "C5"},
    {std::string("HIS+N"), "NH1"},    {std::string("HIS+ND1"), "NH1S"}, {std::string("HIS+NE2"), "NH1S"},
    {std::string("HIS+O"), "O"},      {std::string("HIS+OXT"), "O"},    {std::string("HIS+H"), "H"},
    {std::string("HIS+HA"), "H"},     {std::string("HIS+HB2"), "H"},    {std::string("HIS+HB3"), "H"},
    {std::string("HIS+HD1"), "H"},    {std::string("HIS+HD2"), "H"},    {std::string("HIS+HE1"), "H"},

    {std::string("HOH+O"), "HOH"},    {std::string("HOH+H"), "HOH"},

    {std::string("ILE+C"), "C"},      {std::string("ILE+CA"), "CH1E"},  {std::string("ILE+CB"), "CH1S"},
    {std::string("ILE+CD1"), "CH3E"}, {std::string("ILE+CG1"), "CH2E"}, {std::string("ILE+CG2"), "CH3E"},
    {std::string("ILE+N"), "NH1"},    {std::string("ILE+O"), "O"},      {std::string("ILE+OXT"), "O"},
    {std::string("ILE+H"), "H"},      {std::string("ILE+HA"), "H"},     {std::string("ILE+HB"), "H"},
    {std::string("ILE+HG12"), "H"},   {std::string("ILE+HG13"), "H"},   {std::string("ILE+HG21"), "H"},
    {std::string("ILE+HG22"), "H"},   {std::string("ILE+HG23"), "H"},   {std::string("ILE+HD11"), "H"},
    {std::string("ILE+HD12"), "H"},   {std::string("ILE+HD13"), "H"},

    {std::string("LEU+C"), "C"},      {std::string("LEU+CA"), "CH1E"},  {std::string("LEU+CB"), "CH2E"},
    {std::string("LEU+CD1"), "CH3E"}, {std::string("LEU+CD2"), "CH3E"}, {std::string("LEU+CG"), "CH1S"},
    {std::string("LEU+N"), "NH1"},    {std::string("LEU+O"), "O"},      {std::string("LEU+H"), "H"},
    {std::string("LEU+HA"), "H"},     {std::string("LEU+HB2"), "H"},    {std::string("LEU+HB3"), "H"},
    {std::string("LEU+HD11"), "H"},   {std::string("LEU+HD12"), "H"},   {std::string("LEU+HD13"), "H"},
    {std::string("LEU+HD21"), "H"},   {std::string("LEU+HD22"), "H"},   {std::string("LEU+HD23"), "H"},
    {std::string("LEU+HG"), "H"},

    {std::string("LYS+C"), "C"},      {std::string("LYS+CA"), "CH1E"},  {std::string("LYS+CB"), "CH2E"},
    {std::string("LYS+CD"), "CH2E"},  {std::string("LYS+CE"), "CH2E"},  {std::string("LYS+CG"), "CH2E"},
    {std::string("LYS+N"), "NH1"},    {std::string("LYS+NZ"), "NH3"},   {std::string("LYS+O"), "O"},
    {std::string("LYS+OXT"), "O"},    {std::string("LYS+H"), "H"},      {std::string("LYS+HA"), "H"},
    {std::string("LYS+HB2"), "H"},    {std::string("LYS+HB3"), "H"},    {std::string("LYS+HG2"), "H"},
    {std::string("LYS+HG3"), "H"},    {std::string("LYS+HD2"), "H"},    {std::string("LYS+HD3"), "H"},
    {std::string("LYS+HE2"), "H"},    {std::string("LYS+HE3"), "H"},

    {std::string("MET+C"), "C"},      {std::string("MET+CA"), "CH1E"},  {std::string("MET+CB"), "CH2E"},
    {std::string("MET+CE"), "CH3E"},  {std::string("MET+CG"), "CH2E"},  {std::string("MET+N"), "NH1"},
    {std::string("MET+O"), "O"},      {std::string("MET+SD"), "SM"},    {std::string("MET+OXT"), "O"},
    {std::string("MET+H"), "H"},

    {std::string("PHE+C"), "C"},      {std::string("PHE+CA"), "CH1E"},  {std::string("PHE+CB"), "CH2E"},
    {std::string("PHE+CD1"), "CR1E"}, {std::string("PHE+CD2"), "CR1E"}, {std::string("PHE+CE1"), "CR1E"},
    {std::string("PHE+CE2"), "CR1E"}, {std::string("PHE+CG"), "CF"},    {std::string("PHE+CZ"), "CR1E"},
    {std::string("PHE+N"), "NH1"},    {std::string("PHE+O"), "O"},      {std::string("PHE+OXT"), "O"},
    {std::string("PHE+H"), "H"},      {std::string("PHE+HA"), "H"},     {std::string("PHE+HB2"), "H"},
    {std::string("PHE+HB3"), "H"},    {std::string("PHE+HD1"), "H"},    {std::string("PHE+HD2"), "H"},
    {std::string("PHE+HE1"), "H"},    {std::string("PHE+HE2"), "H"},    {std::string("PHE+HZ"), "H"},

    {std::string("PRO+C"), "C"},      {std::string("PRO+CA"), "CH1E"},  {std::string("PRO+CB"), "CH2E"},
    {std::string("PRO+CD"), "CH2P"},  {std::string("PRO+CG"), "CH2P"},  {std::string("PRO+N"), "N"},
    {std::string("PRO+O"), "O"},      {std::string("PRO+OXT"), "O"},    {std::string("PRO+H"), "H"},
    {std::string("PRO+HA"), "H"},     {std::string("PRO+HB2"), "H"},    {std::string("PRO+HB3"), "H"},
    {std::string("PRO+HD2"), "H"},    {std::string("PRO+HD3"), "H"},    {std::string("PRO+HG2"), "H"},
    {std::string("PRO+HG3"), "H"},

    {std::string("SER+C"), "C"},      {std::string("SER+CA"), "CH1E"},  {std::string("SER+CB"), "CH2E"},
    {std::string("SER+N"), "NH1"},    {std::string("SER+O"), "O"},      {std::string("SER+OG"), "OH1"},
    {std::string("SER+OXT"), "O"},    {std::string("SER+H"), "H"},      {std::string("SER+HA"), "H"},
    {std::string("SER+HB2"), "H"},    {std::string("SER+HB3"), "H"},

    {std::string("THR+C"), "C"},      {std::string("THR+CA"), "CH1E"},  {std::string("THR+CB"), "CH1S"},
    {std::string("THR+CG2"), "CH3E"}, {std::string("THR+N"), "NH1"},    {std::string("THR+O"), "O"},
    {std::string("THR+OG1"), "OH1"},  {std::string("THR+OXT"), "O"},    {std::string("THR+H"), "H"},
    {std::string("THR+HA"), "H"},     {std::string("THR+HB"), "H"},     {std::string("THR+HG1"), "H"},
    {std::string("THR+HG21"), "H"},   {std::string("THR+HG22"), "H"},   {std::string("THR+HG23"), "H"},
    {std::string("THR+HH2"), "H"},

    {std::string("TRP+C"), "C"},      {std::string("TRP+CA"), "CH1E"},  {std::string("TRP+CB"), "CH2E"},
    {std::string("TRP+CD1"), "CR1E"}, {std::string("TRP+CD2"), "CW"},   {std::string("TRP+CE2"), "CW"},
    {std::string("TRP+CE3"), "CR1E"}, {std::string("TRP+CG"), "C5W"},   {std::string("TRP+CH2"), "CR1W"},
    {std::string("TRP+CZ2"), "CR1W"}, {std::string("TRP+CZ3"), "CR1E"}, {std::string("TRP+N"), "NH1"},
    {std::string("TRP+NE1"), "NH1S"}, {std::string("TRP+O"), "O"},      {std::string("TRP+OXT"), "O"},
    {std::string("TRP+H"), "H"},      {std::string("TRP+HA"), "H"},     {std::string("TRP+HB2"), "H"},
    {std::string("TRP+HB3"), "H"},    {std::string("TRP+HD1"), "H"},    {std::string("TRP+HE1"), "H"},
    {std::string("TRP+HE3"), "H"},    {std::string("TRP+HZ2"), "H"},    {std::string("TRP+HZ3"), "H"},
    {std::string("TRP+HH2"), "H"},

    {std::string("TYR+C"), "C"},      {std::string("TYR+CA"), "CH1E"},  {std::string("TYR+CB"), "CH2E"},
    {std::string("TYR+CD1"), "CR1E"}, {std::string("TYR+CD2"), "CR1E"}, {std::string("TYR+CE1"), "CR1E"},
    {std::string("TYR+CE2"), "CR1E"}, {std::string("TYR+CG"), "CY"},    {std::string("TYR+CZ"), "CY2"},
    {std::string("TYR+N"), "NH1"},    {std::string("TYR+O"), "O"},      {std::string("TYR+OH"), "OH1"},
    {std::string("TYR+OXT"), "O"},    {std::string("TYR+H"), "H"},      {std::string("TYR+HA"), "H"},
    {std::string("TYR+HB2"), "H"},    {std::string("TYR+HB3"), "H"},    {std::string("TYR+HD1"), "H"},
    {std::string("TYR+HD2"), "H"},    {std::string("TYR+HE1"), "H"},    {std::string("TYR+HE2"), "H"},

    {std::string("VAL+C"), "C"},      {std::string("VAL+CA"), "CH1E"},  {std::string("VAL+CB"), "CH1S"},
    {std::string("VAL+CG1"), "CH3E"}, {std::string("VAL+CG2"), "CH3E"}, {std::string("VAL+N"), "NH1"},
    {std::string("VAL+O"), "O"},      {std::string("VAL+OXT"), "O"},    {std::string("VAL+H"), "H"},
    {std::string("VAL+HA"), "H"},     {std::string("VAL+HB"), "H"},     {std::string("VAL+HG11"), "H"},
    {std::string("VAL+HG12"), "H"},   {std::string("VAL+HG13"), "H"},   {std::string("VAL+HG21"), "H"},
    {std::string("VAL+HG22"), "H"},   {std::string("VAL+HG23"), "H"}};

std::map<std::string, std::vector<std::string>> PredefinedElements::residueDefinitionsBondedAtoms = {
    {std::string("ALA+C"), {"CA", "O"}},
    {std::string("ALA+CA"), {"N", "CB", "C"}},
    {std::string("ALA+CB"), {"CA"}},
    {std::string("ALA+N"), {"-C", "CA"}},
    {std::string("ALA+O"), {"C"}},
    {std::string("ALA+OXT"), {"C"}},
    {std::string("ALA+H"), {}},
    {std::string("ALA+HA"), {}},
    {std::string("ALA+HB1"), {}},
    {std::string("ALA+HB2"), {}},
    {std::string("ALA+HB3"), {}},

    {std::string("ARG+C"), {"CA", "O"}},
    {std::string("ARG+CA"), {"N ", "CB ", "C"}},
    {std::string("ARG+CB"), {"CA", "CG"}},
    {std::string("ARG+CD"), {"CG", "NE"}},
    {std::string("ARG+CG"), {"CB", "CD"}},
    {std::string("ARG+CZ"), {"NE", " NH1", "NH2"}},
    {std::string("ARG+N"), {"-C", "CA"}},
    {std::string("ARG+NE"), {"CD", "CZ"}},
    {std::string("ARG+NH1"), {"CZ"}},
    {std::string("ARG+NH2"), {"CZ"}},
    {std::string("ARG+O"), {"C"}},
    {std::string("ARG+OXT"), {"C"}},
    {std::string("ARG+H"), {}},
    {std::string("ARG+HA"), {}},
    {std::string("ARG+HB2"), {}},
    {std::string("ARG+HB3"), {}},
    {std::string("ARG+HD2"), {}},
    {std::string("ARG+HD3"), {}},
    {std::string("ARG+HE"), {}},
    {std::string("ARG+HG2"), {}},
    {std::string("ARG+HG3"), {}},
    {std::string("ARG+HH11"), {}},
    {std::string("ARG+HH12"), {}},
    {std::string("ARG+HH21"), {}},
    {std::string("ARG+HH22"), {}},

    {std::string("ASN+C"), {"CA", "O"}},
    {std::string("ASN+CA"), {"N", "CB", "C"}},
    {std::string("ASN+CB"), {"CA", "CG"}},
    {std::string("ASN+CG"), {"CB", "OD1", "ND2"}},
    {std::string("ASN+N"), {"-C", "CA"}},
    {std::string("ASN+ND2"), {"CG"}},
    {std::string("ASN+O"), {"C"}},
    {std::string("ASN+OD1"), {"CG"}},
    {std::string("ASN+OXT"), {"C"}},
    {std::string("ASN+H"), {}},
    {std::string("ASN+HA"), {}},
    {std::string("ASN+HB2"), {}},
    {std::string("ASN+HB3"), {}},
    {std::string("ASN+HD21"), {}},
    {std::string("ASN+HD22"), {}},

    {std::string("ASP+C"), {"CA", "O"}},
    {std::string("ASP+CA"), {"N ", "CB", "C"}},
    {std::string("ASP+CB"), {"CA ", "CG"}},
    {std::string("ASP+CG"), {"CB ", "OD1", "OD2"}},
    {std::string("ASP+N"), {"-C ", "CA"}},
    {std::string("ASP+O"), {"C"}},
    {std::string("ASP+OD1"), {"CG"}},
    {std::string("ASP+OD2"), {"CG"}},
    {std::string("ASP+OXT"), {"C"}},
    {std::string("ASP+H"), {}},
    {std::string("ASP+HA"), {}},
    {std::string("ASP+HB2"), {}},
    {std::string("ASP+HB3"), {}},

    {std::string("CYS+C"), {"CA", "O"}},
    {std::string("CYS+CA"), {"N", "CB ", "C"}},
    {std::string("CYS+CB"), {"CA", "SG"}},
    {std::string("CYS+N"), {"-C", "CA"}},
    {std::string("CYS+O"), {"C"}},
    {std::string("CYS+SG"), {"CB"}},
    {std::string("CYS+OXT"), {"C"}},
    {std::string("CYS+H"), {}},
    {std::string("CYS+HA"), {}},
    {std::string("CYS+HB2"), {}},
    {std::string("CYS+HB3"), {}},

    {std::string("GLN+C"), {"CA", "O"}},
    {std::string("GLN+CA"), {"N", "CB", "C"}},
    {std::string("GLN+CB"), {"CA ", "CG"}},
    {std::string("GLN+CD"), {"CG", "NE2", "OE1"}},
    {std::string("GLN+CG"), {"CB", "CD"}},
    {std::string("GLN+N"), {"-C ", "CA"}},
    {std::string("GLN+NE2"), {"CD"}},
    {std::string("GLN+O"), {"C"}},
    {std::string("GLN+OE1"), {"CD"}},
    {std::string("GLN+OXT"), {"C"}},
    {std::string("GLN+H"), {}},
    {std::string("GLN+HA"), {}},
    {std::string("GLN+HB2"), {}},
    {std::string("GLN+HB3"), {}},
    {std::string("GLN+HG2"), {}},
    {std::string("GLN+HG3"), {}},
    {std::string("GLN+HE21"), {}},
    {std::string("GLN+HE22"), {}},

    {std::string("GLU+C"), {"CA", "O"}},
    {std::string("GLU+CA"), {"N", "CB", "C"}},
    {std::string("GLU+CB"), {"CA", "CG"}},
    {std::string("GLU+CD"), {"CG", "OE1 ", "OE2"}},
    {std::string("GLU+CG"), {"CB ", "CD"}},
    {std::string("GLU+N"), {"-C", "CA"}},
    {std::string("GLU+O"), {"C"}},
    {std::string("GLU+OE1"), {"CD"}},
    {std::string("GLU+OE2"), {"CD"}},
    {std::string("GLU+OXT"), {"C"}},
    {std::string("GLU+H"), {}},
    {std::string("GLU+HA"), {}},
    {std::string("GLU+HB2"), {}},
    {std::string("GLU+HB3"), {}},
    {std::string("GLU+HG2"), {}},
    {std::string("GLU+HG3"), {}},

    {std::string("GLY+C"), {"CA", "O"}},
    {std::string("GLY+CA"), {"N", "C"}},
    {std::string("GLY+N"), {"-C", "CA"}},
    {std::string("GLY+O"), {"C"}},
    {std::string("GLY+OXT"), {"C"}},
    {std::string("GLY+H"), {}},
    {std::string("GLY+HA"), {}},
    {std::string("GLY+HA2"), {}},
    {std::string("GLY+HA3"), {}},
    {std::string("GLY+HB2"), {}},
    {std::string("GLY+HB3"), {}},
    {std::string("GLY+HG2"), {}},
    {std::string("GLY+HG3"), {}},

    {std::string("HIS+C"), {"CA", "O"}},
    {std::string("HIS+CA"), {"N", "CB", "C"}},
    {std::string("HIS+CB"), {"CA", "CG"}},
    {std::string("HIS+CD2"), {"CG ", "NE2"}},
    {std::string("HIS+CE1"), {"ND1", "NE2"}},
    {std::string("HIS+CG"), {"CB", "CD2", "ND1"}},
    {std::string("HIS+N"), {"-C", "CA"}},
    {std::string("HIS+ND1"), {"CG ", "CE1"}},
    {std::string("HIS+NE2"), {"CD2", "CE1"}},
    {std::string("HIS+O"), {"C"}},
    {std::string("HIS+OXT"), {"C"}},
    {std::string("HIS+H"), {}},
    {std::string("HIS+HA"), {}},
    {std::string("HIS+HB2"), {}},
    {std::string("HIS+HB3"), {}},
    {std::string("HIS+HD1"), {}},
    {std::string("HIS+HD2"), {}},
    {std::string("HIS+HE1"), {}},

    {std::string("HOH+O"), {}},
    {std::string("HOH+H"), {}},

    {std::string("ILE+C"), {"CA", "O"}},
    {std::string("ILE+CA"), {"N ", "CB ", "C"}},
    {std::string("ILE+CB"), {"CA", "CG1", "CG2"}},
    {std::string("ILE+CD1"), {"CG1"}},
    {std::string("ILE+CG1"), {"CB ", "CD1"}},
    {std::string("ILE+CG2"), {"CB"}},
    {std::string("ILE+N"), {"-C", "CA"}},
    {std::string("ILE+O"), {"C"}},
    {std::string("ILE+OXT"), {"C"}},
    {std::string("ILE+H"), {}},
    {std::string("ILE+HA"), {}},
    {std::string("ILE+HB"), {}},
    {std::string("ILE+HG12"), {}},
    {std::string("ILE+HG13"), {}},
    {std::string("ILE+HG21"), {}},
    {std::string("ILE+HG22"), {}},
    {std::string("ILE+HG23"), {}},
    {std::string("ILE+HD11"), {}},
    {std::string("ILE+HD12"), {}},
    {std::string("ILE+HD13"), {}},

    {std::string("LEU+C"), {"CA", "O"}},
    {std::string("LEU+CA"), {"N ", "CB", "C"}},
    {std::string("LEU+CB"), {"CA ", "CG"}},
    {std::string("LEU+CD1"), {"CG"}},
    {std::string("LEU+CD2"), {"CG"}},
    {std::string("LEU+CG"), {"CB ", "CD1", "CD2"}},
    {std::string("LEU+N"), {"-C ", "CA"}},
    {std::string("LEU+O"), {"C"}},
    {std::string("LEU+H"), {}},
    {std::string("LEU+HA"), {}},
    {std::string("LEU+HB2"), {}},
    {std::string("LEU+HB3"), {}},
    {std::string("LEU+HD11"), {}},
    {std::string("LEU+HD12"), {}},
    {std::string("LEU+HD13"), {}},
    {std::string("LEU+HD21"), {}},
    {std::string("LEU+HD22"), {}},
    {std::string("LEU+HD23"), {}},
    {std::string("LEU+HG"), {}},

    {std::string("LYS+C"), {"CA ", "O"}},
    {std::string("LYS+CA"), {"N ", "CB", "C"}},
    {std::string("LYS+CB"), {"CA ", "CG"}},
    {std::string("LYS+CD"), {"CG ", "CE"}},
    {std::string("LYS+CE"), {"CD ", "NZ"}},
    {std::string("LYS+CG"), {"CB ", "CD"}},
    {std::string("LYS+N"), {"-C  ", "CA"}},
    {std::string("LYS+NZ"), {"CE"}},
    {std::string("LYS+O"), {"C"}},
    {std::string("LYS+OXT"), {"C"}},
    {std::string("LYS+H"), {}},
    {std::string("LYS+HA"), {}},
    {std::string("LYS+HB2"), {}},
    {std::string("LYS+HB3"), {}},
    {std::string("LYS+HG2"), {}},
    {std::string("LYS+HG3"), {}},
    {std::string("LYS+HD2"), {}},
    {std::string("LYS+HD3"), {}},
    {std::string("LYS+HE2"), {}},
    {std::string("LYS+HE3"), {}},

    {std::string("MET+C"), {"CA ", "O"}},
    {std::string("MET+CA"), {"N", "CB", "C"}},
    {std::string("MET+CB"), {"CA ", "CG"}},
    {std::string("MET+CE"), {"SD"}},
    {std::string("MET+CG"), {"CB ", "SD"}},
    {std::string("MET+N"), {"-C", "CA"}},
    {std::string("MET+O"), {"C"}},
    {std::string("MET+SD"), {"CG ", "CE"}},
    {std::string("MET+OXT"), {"C"}},
    {std::string("MET+H"), {}},

    {std::string("PHE+C"), {"CA", "O"}},
    {std::string("PHE+CA"), {"N", "CB", "C"}},
    {std::string("PHE+CB"), {"CA", "CG"}},
    {std::string("PHE+CD1"), {"CG ", "CE1"}},
    {std::string("PHE+CD2"), {"CG ", "CE2"}},
    {std::string("PHE+CE1"), {"CD1", "CZ"}},
    {std::string("PHE+CE2"), {"CD2 ", "CZ"}},
    {std::string("PHE+CG"), {"CB ", "CD1", "CD2"}},
    {std::string("PHE+CZ"), {"CE1", "CE2"}},
    {std::string("PHE+N"), {"-C ", "CA"}},
    {std::string("PHE+O"), {"C"}},
    {std::string("PHE+OXT"), {"C"}},
    {std::string("PHE+H"), {}},
    {std::string("PHE+HA"), {}},
    {std::string("PHE+HB2"), {}},
    {std::string("PHE+HB3"), {}},
    {std::string("PHE+HD1"), {}},
    {std::string("PHE+HD2"), {}},
    {std::string("PHE+HE1"), {}},
    {std::string("PHE+HE2"), {}},
    {std::string("PHE+HZ"), {}},

    {std::string("PRO+C"), {"CA", "O"}},
    {std::string("PRO+CA"), {"N", "CB", "C"}},
    {std::string("PRO+CB"), {"CA", "CG"}},
    {std::string("PRO+CD"), {"N", "CG"}},
    {std::string("PRO+CG"), {"CB", "CD"}},
    {std::string("PRO+N"), {"-C", "CA", "CD"}},
    {std::string("PRO+O"), {"C"}},
    {std::string("PRO+OXT"), {"C"}},
    {std::string("PRO+H"), {}},
    {std::string("PRO+HA"), {}},
    {std::string("PRO+HB2"), {}},
    {std::string("PRO+HB3"), {}},
    {std::string("PRO+HD2"), {}},
    {std::string("PRO+HD3"), {}},
    {std::string("PRO+HG2"), {}},
    {std::string("PRO+HG3"), {}},

    {std::string("SER+C"), {"CA", "O"}},
    {std::string("SER+CA"), {"N", "CB", "C"}},
    {std::string("SER+CB"), {"CA", "OG"}},
    {std::string("SER+N"), {"-C", "CA"}},
    {std::string("SER+O"), {"C"}},
    {std::string("SER+OG"), {"CB"}},
    {std::string("SER+OXT"), {"C"}},
    {std::string("SER+H"), {}},
    {std::string("SER+HA"), {}},
    {std::string("SER+HB2"), {}},
    {std::string("SER+HB3"), {}},

    {std::string("THR+C"), {"CA", "O"}},
    {std::string("THR+CA"), {"N", "CB", "C"}},
    {std::string("THR+CB"), {"CA", "CG2", "OG1"}},
    {std::string("THR+CG2"), {"CB"}},
    {std::string("THR+N"), {"-C", "CA"}},
    {std::string("THR+O"), {"C"}},
    {std::string("THR+OG1"), {"CB"}},
    {std::string("THR+OXT"), {"C"}},
    {std::string("THR+H"), {}},
    {std::string("THR+HA"), {}},
    {std::string("THR+HB"), {}},
    {std::string("THR+HG1"), {}},
    {std::string("THR+HG21"), {}},
    {std::string("THR+HG22"), {}},
    {std::string("THR+HG23"), {}},
    {std::string("THR+HH2"), {}},

    {std::string("TRP+C"), {"CA", "O"}},
    {std::string("TRP+CA"), {"N ", "CB", "C"}},
    {std::string("TRP+CB"), {"CA", "CG"}},
    {std::string("TRP+CD1"), {"CG ", "NE1"}},
    {std::string("TRP+CD2"), {"CG ", " CE2", "CE3"}},
    {std::string("TRP+CE2"), {"CD2 ", "CZ2", "NE1"}},
    {std::string("TRP+CE3"), {"CD2", "CZ3"}},
    {std::string("TRP+CG"), {"CB ", "CD1", "CD2"}},
    {std::string("TRP+CH2"), {"CZ2", "CZ3"}},
    {std::string("TRP+CZ2"), {"CE2", "CH2"}},
    {std::string("TRP+CZ3"), {"CE3", "CH2"}},
    {std::string("TRP+N"), {"-C", "CA"}},
    {std::string("TRP+NE1"), {"CD1 ", "CE2"}},
    {std::string("TRP+O"), {"C"}},
    {std::string("TRP+OXT"), {"C"}},
    {std::string("TRP+H"), {}},
    {std::string("TRP+HA"), {}},
    {std::string("TRP+HB2"), {}},
    {std::string("TRP+HB3"), {}},
    {std::string("TRP+HD1"), {}},
    {std::string("TRP+HE1"), {}},
    {std::string("TRP+HE3"), {}},
    {std::string("TRP+HZ2"), {}},
    {std::string("TRP+HZ3"), {}},
    {std::string("TRP+HH2"), {}},

    {std::string("TYR+C"), {"CA", "O"}},
    {std::string("TYR+CA"), {"N", "CB", "C"}},
    {std::string("TYR+CB"), {"CA", "CG"}},
    {std::string("TYR+CD1"), {"CG", "CE1"}},
    {std::string("TYR+CD2"), {"CG", "CE2"}},
    {std::string("TYR+CE1"), {"CD1", "CZ"}},
    {std::string("TYR+CE2"), {"CD2", "CZ"}},
    {std::string("TYR+CG"), {"CB", "CD1", "CD2"}},
    {std::string("TYR+CZ"), {"CE1", "CE2", "OH"}},
    {std::string("TYR+N"), {"-C", "CA"}},
    {std::string("TYR+O"), {"C"}},
    {std::string("TYR+OH"), {"CZ"}},
    {std::string("TYR+OXT"), {"C"}},
    {std::string("TYR+H"), {}},
    {std::string("TYR+HA"), {}},
    {std::string("TYR+HB2"), {}},
    {std::string("TYR+HB3"), {}},
    {std::string("TYR+HD1"), {}},
    {std::string("TYR+HD2"), {}},
    {std::string("TYR+HE1"), {}},
    {std::string("TYR+HE2"), {}},

    {std::string("VAL+C"), {"CA", "O"}},
    {std::string("VAL+CA"), {"N", "CB", "C"}},
    {std::string("VAL+CB"), {"CA", "CG1", "CG2"}},
    {std::string("VAL+CG1"), {"CB"}},
    {std::string("VAL+CG2"), {"CB"}},
    {std::string("VAL+N"), {"-C", "CA"}},
    {std::string("VAL+O"), {"C"}},
    {std::string("VAL+OXT"), {"C"}},
    {std::string("VAL+H"), {}},
    {std::string("VAL+HA"), {}},
    {std::string("VAL+HB"), {}},
    {std::string("VAL+HG11"), {}},
    {std::string("VAL+HG12"), {}},
    {std::string("VAL+HG13"), {}},
    {std::string("VAL+HG21"), {}},
    {std::string("VAL+HG22"), {}},
    {std::string("VAL+HG23"), {}}};
