# Run at build time (cmake -P) to write the translation unit that tells the binary which source it was
# built from. It runs on every build, but rewrites the output only when the answer changes, so the file
# is recompiled -- and the executable relinked -- only when the commit or the dirty state moves.
#
# Inputs: SOURCE_DIR, OUTPUT, VERSION.

set(commit "unknown")
set(commit_date "unknown")
set(tree_state "")

find_package(Git QUIET)
if(GIT_EXECUTABLE)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=10 HEAD
    OUTPUT_VARIABLE git_commit
    RESULT_VARIABLE git_result
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
  if(git_result EQUAL 0)
    set(commit "${git_commit}")

    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" log -1 --format=%ci HEAD
      OUTPUT_VARIABLE commit_date
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)

    # Tracked files only: scratch output lying around the tree does not make the build a different one.
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
      OUTPUT_VARIABLE git_status
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)
    if(NOT git_status STREQUAL "")
      set(tree_state ", with uncommitted changes")
    endif()
  endif()
endif()

set(content "// Generated by src/raspakit/build_info.cmake at build time. Do not edit.
#include \"build_info.h\"

namespace BuildInfoData
{
const char *const version = \"${VERSION}\";
const char *const commit = \"${commit}\";
const char *const commitDate = \"${commit_date}\";
const char *const treeState = \"${tree_state}\";
const char *const compileDate = __DATE__ \" \" __TIME__;
}  // namespace BuildInfoData
")

file(WRITE "${OUTPUT}.tmp" "${content}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
