#pragma once

#include <algorithm>
#include <any>
#include <array>
#include <cassert>
#include <cctype>
#include <climits>
#include <cerrno>
#include <clocale>
#include <cmath>
#include <compare>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <exception>
#include <filesystem>
#include <forward_list>
#include <functional>
#include <functional>
#include <initializer_list>
#include <iomanip>
#include <iosfwd>
#include <iterator>
#include <limits>
#include <bitset>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <ranges>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <valarray>
#include <vector>
#include <version>
#include <iosfwd>
#include <errno.h>
#include <stdio.h>
#include <cassert>
#include <mutex>
#include <thread>
#include <future>
#include <semaphore>
#include <bit>
#include <complex>
#include <deque>
#include <unordered_set>
#include <set>
#include <source_location>
#include <fstream>
#include <istream>
#include <iostream>
#include <sstream>
#include <format>
#include <print>
#include <chrono>
#include <numbers>
#include <random>
