name: check pr

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  check-build:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install packages
        shell: bash
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Europe/Amsterdam apt-get -y install tzdata 
          apt-get install -y --no-install-recommends git ca-certificates cmake ninja-build wget
          apt-get install -y --no-install-recommends llvm lld clang clang-tools clang-tidy libc++-dev libc++abi-dev libomp-dev libclang-rt-dev
          apt-get install -y --no-install-recommends python3 pybind11-dev python3-pybind11 python3-dev
          apt-get install -y --no-install-recommends liblapack64-dev libblas64-dev 
          wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.4.3/hdf5.tar.gz
          tar -zxvf hdf5.tar.gz
          cd hdf5-1.14.4-3
          cmake -B build -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/usr -DHDF5_BUILD_CPP_LIB=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -std=c++23 -stdlib=libc++" -DZLIB_LIBRARY=/usr/lib/x86_64-linux-gnu/libz.a -DHDF5_ENABLE_NONSTANDARD_FEATURE_FLOAT16=OFF
          ninja -C build
          ninja -C build install
          cd ..
          rm -rf hdf5-1.14.4-3
          ldconfig
          cmake -B ${{github.workspace}}/build --preset linux-x86_64-ubuntu-24
      - name: configure cmake raspa3 
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build --preset linux-x86_64-ubuntu-24 .
