name: create-doxygen-documentation
on:
  workflow_dispatch:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iraspa/ubuntu-24-x86_64-llvm-22:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: install-packages
        shell: bash
        run: |
          apt-get update
          apt-get install -y --no-install-recommends doxygen graphviz
      - name: configure-cmake-raspa3 
        shell: bash
        run: |
          cmake -B ${{github.workspace}}/build --preset linux-x86_64-core-avx2-ubuntu-24 -DBUILD_DOXYGEN=ON .
          cmake --build ${{github.workspace}}/build -t documentation
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/build/html

