name: Create Release Rocky-8
on:
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      tag-name:
        description: 'Name of the tag that will be used for this release'
        required: true

jobs:
  release-job:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag-name }}
        release_name: Release ${{ github.event.inputs.tag-name }}
        draft: false
        prerelease: false
    - name: set upload_url output
      id: step_upload_url
      run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_OUTPUT"


  rocky-8-job:
    runs-on: ubuntu-latest
    needs: release-job
    container:
      image: ghcr.io/iraspa/rocky-8-llvm-18:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: configure cmake raspa
        shell: bash
        run: |
          yum install -y blas64
          cmake -B ${{github.workspace}}/build -GNinja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_RPM_PACKAGE=ON -DBLAS_LIBRARIES=/usr/lib64/libblas64_.so.3 -DLAPACK_LIBRARIES=/usr/lib64/liblapack64_.so.3 .
      - name: create raspa rpm package
        shell: bash
        run: |
          ninja -C ${{github.workspace}}/build package
          mv ${{github.workspace}}/build/raspa-3.0.0-1.el8.x86_64.rpm .
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-job.outputs.upload_url }}
          asset_path: ./raspa-3.0.0-1.el8.x86_64.rpm
          asset_name: raspa-3.0.0-1.el8.x86_64.rpm
          asset_content_type: application/octet-stream
