name: publish pypi
on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build-macos-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install MacOS dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install llvm cmake ninja libomp
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Set preset
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "macos-14" ]]; then
          echo "CMAKE_PRESET=--preset=macos-apple-silicon" >> $GITHUB_ENV
        else
          echo "CMAKE_PRESET=--preset=macos-intel" >> $GITHUB_ENV
        fi

    - name: Build package
      run: |
        python -m build -w

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    runs-on: ubuntu-24.04
    needs: 
      - build-macos-packages
    environment:
      name: pypi
      url: https://test.pypi.org/p/raspa
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
